#dbUserPasswords:
#  dbuserPassword: ""

databases:
  inji_certify_incra:
    enabled: true
    host: "inji-postgres-rds.c9w0c8mus9uc.ap-south-1.rds.amazonaws.com"
    port: 5432
    su:
      user: postgres
      secret:
        name: postgres-postgresql
        key: postgres-password
    dml: 1
    repoUrl: "https://github.com/kamalnanda21/inji-certify.git"
    branch: db-scripts-kamal